package com.bpf.vo;

import com.bpf.pojo.Owner;
import com.bpf.pojo.PageWithBLOBs;

import java.io.Serializable;
import java.util.List;

public class CourseVo implements Serializable {

    private Owner owner;

    private List<PageWithBLOBs> pageList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.bvid
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    private String bvid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.aid
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    private String aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.title
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.videos
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    private Integer videos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.ownerid
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    private Integer ownerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.saved
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    private Integer saved;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.intro
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    private static final long serialVersionUID = 1L;

    public Owner getOwner() {
        return owner;
    }

    public void setOwner(Owner owner) {
        this.owner = owner;
    }

    public List<PageWithBLOBs> getPageList() {
        return pageList;
    }

    public void setPageList(List<PageWithBLOBs> pageList) {
        this.pageList = pageList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.bvid
     *
     * @return the value of course.bvid
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public String getBvid() {
        return bvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.bvid
     *
     * @param bvid the value for course.bvid
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public void setBvid(String bvid) {
        this.bvid = bvid == null ? null : bvid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.aid
     *
     * @return the value of course.aid
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public String getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.aid
     *
     * @param aid the value for course.aid
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public void setAid(String aid) {
        this.aid = aid == null ? null : aid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.title
     *
     * @return the value of course.title
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.title
     *
     * @param title the value for course.title
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.videos
     *
     * @return the value of course.videos
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public Integer getVideos() {
        return videos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.videos
     *
     * @param videos the value for course.videos
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public void setVideos(Integer videos) {
        this.videos = videos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.ownerid
     *
     * @return the value of course.ownerid
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public Integer getOwnerid() {
        return ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.ownerid
     *
     * @param ownerid the value for course.ownerid
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public void setOwnerid(Integer ownerid) {
        this.ownerid = ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.saved
     *
     * @return the value of course.saved
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public Integer getSaved() {
        return saved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.saved
     *
     * @param saved the value for course.saved
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public void setSaved(Integer saved) {
        this.saved = saved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.intro
     *
     * @return the value of course.intro
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.intro
     *
     * @param intro the value for course.intro
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bvid=").append(bvid);
        sb.append(", aid=").append(aid);
        sb.append(", title=").append(title);
        sb.append(", videos=").append(videos);
        sb.append(", ownerid=").append(ownerid);
        sb.append(", saved=").append(saved);
        sb.append(", intro=").append(intro);
        sb.append("]");
        return sb.toString();
    }
}