package com.bpf.mapper;

import com.bpf.pojo.Page;
import com.bpf.pojo.PageExample;
import com.bpf.pojo.PageWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    long countByExample(PageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    int deleteByExample(PageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    int deleteByPrimaryKey(String cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    int insert(PageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    int insertSelective(PageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    List<PageWithBLOBs> selectByExampleWithBLOBs(PageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    List<Page> selectByExample(PageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    PageWithBLOBs selectByPrimaryKey(String cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    int updateByExampleSelective(@Param("record") PageWithBLOBs record, @Param("example") PageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") PageWithBLOBs record, @Param("example") PageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    int updateByExample(@Param("record") Page record, @Param("example") PageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    int updateByPrimaryKeySelective(PageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(PageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    int updateByPrimaryKey(Page record);
}