server:
  port: 8090
  servlet:
    context-path: /blbldl

spring:
  # \u6570\u636E\u6E90
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blbldl?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1   # \u521D\u59CB\u8FDE\u63A5\u6570
      max-active: 20    # \u6700\u5927\u8FDE\u63A5\u6570
      max-idle: 20      # \u6700\u5927\u7A7A\u95F2
      min-idle: 1       # \u6700\u5C0F\u7A7A\u95F2
      max-wait: 60000   # \u6700\u957F\u7B49\u5F85\u65F6\u95F4

  # \u6A21\u677F\u5F15\u64CE
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html;charset=UTF-8
    enabled: true
    suffix: .ftl
    template-loader-path: classpath:/views/
    # \u6A21\u677F\u5F15\u64CE\u662F\u5426\u53EF\u4EE5\u76F4\u63A5\u83B7\u53D6 request \u57DF\u7684\u5C5E\u6027
    request-context-attribute: request
    expose-request-attributes: true
    expose-spring-macro-helpers: true
    expose-session-attributes: true
    settings:
      tag_syntax: auto_detect     # \u914D\u7F6E\u6807\u7B7E\u8BED\u6CD5\u4E3A\u81EA\u52A8\uFF0C\u9875\u9762\u53EF\u4EE5\u5C06<>\u6539\u4E3A[]\uFF0C\u4E3A\u4E86\u533A\u522Bhtml\u6807\u7B7E
      template_update_delay: 0    # \u6A21\u677F\u66F4\u65B0\u65F6\u95F4\uFF0C\u5355\u4F4D: \u79D2
      default_encoding: UTF-8     # \u9ED8\u8BA4\u7684\u7F16\u7801\u5B57\u7B26\u96C6
      output_encoding: UTF-8      # \u6A21\u677F\u8F93\u51FA\u7684\u7F16\u7801\u5B57\u7B26\u96C6
      locale: zh_CN               # \u672C\u5730\u5316\u914D\u7F6E
      date_format: yyyy-MM-dd     # \u65E5\u671F\u683C\u5F0F\u5316
      time_format: HH:mm:ss       # \u65F6\u95F4\u683C\u5F0F\u5316
      datetime_format: yyyy-MM-dd HH:mm:ss  # \u65E5\u671F\u65F6\u95F4\u683C\u5F0F\u5316
      number_format: #.##         # \u6570\u5B57\u683C\u5F0F\u5316
      boolean_format: true, false # \u5E03\u5C14\u503C\u683C\u5F0F\u5316
      template_exception_handler: html_debug

mybatis:
  type-aliases-package: com.bpf.pojo
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    com.bpf.manager.mapper: debug
