package com.bpf.pojo;

import java.util.ArrayList;
import java.util.List;

public class CourseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public CourseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table course
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBvidIsNull() {
            addCriterion("bvid is null");
            return (Criteria) this;
        }

        public Criteria andBvidIsNotNull() {
            addCriterion("bvid is not null");
            return (Criteria) this;
        }

        public Criteria andBvidEqualTo(String value) {
            addCriterion("bvid =", value, "bvid");
            return (Criteria) this;
        }

        public Criteria andBvidNotEqualTo(String value) {
            addCriterion("bvid <>", value, "bvid");
            return (Criteria) this;
        }

        public Criteria andBvidGreaterThan(String value) {
            addCriterion("bvid >", value, "bvid");
            return (Criteria) this;
        }

        public Criteria andBvidGreaterThanOrEqualTo(String value) {
            addCriterion("bvid >=", value, "bvid");
            return (Criteria) this;
        }

        public Criteria andBvidLessThan(String value) {
            addCriterion("bvid <", value, "bvid");
            return (Criteria) this;
        }

        public Criteria andBvidLessThanOrEqualTo(String value) {
            addCriterion("bvid <=", value, "bvid");
            return (Criteria) this;
        }

        public Criteria andBvidLike(String value) {
            addCriterion("bvid like", value, "bvid");
            return (Criteria) this;
        }

        public Criteria andBvidNotLike(String value) {
            addCriterion("bvid not like", value, "bvid");
            return (Criteria) this;
        }

        public Criteria andBvidIn(List<String> values) {
            addCriterion("bvid in", values, "bvid");
            return (Criteria) this;
        }

        public Criteria andBvidNotIn(List<String> values) {
            addCriterion("bvid not in", values, "bvid");
            return (Criteria) this;
        }

        public Criteria andBvidBetween(String value1, String value2) {
            addCriterion("bvid between", value1, value2, "bvid");
            return (Criteria) this;
        }

        public Criteria andBvidNotBetween(String value1, String value2) {
            addCriterion("bvid not between", value1, value2, "bvid");
            return (Criteria) this;
        }

        public Criteria andAidIsNull() {
            addCriterion("aid is null");
            return (Criteria) this;
        }

        public Criteria andAidIsNotNull() {
            addCriterion("aid is not null");
            return (Criteria) this;
        }

        public Criteria andAidEqualTo(String value) {
            addCriterion("aid =", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotEqualTo(String value) {
            addCriterion("aid <>", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidGreaterThan(String value) {
            addCriterion("aid >", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidGreaterThanOrEqualTo(String value) {
            addCriterion("aid >=", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidLessThan(String value) {
            addCriterion("aid <", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidLessThanOrEqualTo(String value) {
            addCriterion("aid <=", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidLike(String value) {
            addCriterion("aid like", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotLike(String value) {
            addCriterion("aid not like", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidIn(List<String> values) {
            addCriterion("aid in", values, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotIn(List<String> values) {
            addCriterion("aid not in", values, "aid");
            return (Criteria) this;
        }

        public Criteria andAidBetween(String value1, String value2) {
            addCriterion("aid between", value1, value2, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotBetween(String value1, String value2) {
            addCriterion("aid not between", value1, value2, "aid");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andVideosIsNull() {
            addCriterion("videos is null");
            return (Criteria) this;
        }

        public Criteria andVideosIsNotNull() {
            addCriterion("videos is not null");
            return (Criteria) this;
        }

        public Criteria andVideosEqualTo(Integer value) {
            addCriterion("videos =", value, "videos");
            return (Criteria) this;
        }

        public Criteria andVideosNotEqualTo(Integer value) {
            addCriterion("videos <>", value, "videos");
            return (Criteria) this;
        }

        public Criteria andVideosGreaterThan(Integer value) {
            addCriterion("videos >", value, "videos");
            return (Criteria) this;
        }

        public Criteria andVideosGreaterThanOrEqualTo(Integer value) {
            addCriterion("videos >=", value, "videos");
            return (Criteria) this;
        }

        public Criteria andVideosLessThan(Integer value) {
            addCriterion("videos <", value, "videos");
            return (Criteria) this;
        }

        public Criteria andVideosLessThanOrEqualTo(Integer value) {
            addCriterion("videos <=", value, "videos");
            return (Criteria) this;
        }

        public Criteria andVideosIn(List<Integer> values) {
            addCriterion("videos in", values, "videos");
            return (Criteria) this;
        }

        public Criteria andVideosNotIn(List<Integer> values) {
            addCriterion("videos not in", values, "videos");
            return (Criteria) this;
        }

        public Criteria andVideosBetween(Integer value1, Integer value2) {
            addCriterion("videos between", value1, value2, "videos");
            return (Criteria) this;
        }

        public Criteria andVideosNotBetween(Integer value1, Integer value2) {
            addCriterion("videos not between", value1, value2, "videos");
            return (Criteria) this;
        }

        public Criteria andOwneridIsNull() {
            addCriterion("ownerid is null");
            return (Criteria) this;
        }

        public Criteria andOwneridIsNotNull() {
            addCriterion("ownerid is not null");
            return (Criteria) this;
        }

        public Criteria andOwneridEqualTo(Integer value) {
            addCriterion("ownerid =", value, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridNotEqualTo(Integer value) {
            addCriterion("ownerid <>", value, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridGreaterThan(Integer value) {
            addCriterion("ownerid >", value, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridGreaterThanOrEqualTo(Integer value) {
            addCriterion("ownerid >=", value, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridLessThan(Integer value) {
            addCriterion("ownerid <", value, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridLessThanOrEqualTo(Integer value) {
            addCriterion("ownerid <=", value, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridIn(List<Integer> values) {
            addCriterion("ownerid in", values, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridNotIn(List<Integer> values) {
            addCriterion("ownerid not in", values, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridBetween(Integer value1, Integer value2) {
            addCriterion("ownerid between", value1, value2, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridNotBetween(Integer value1, Integer value2) {
            addCriterion("ownerid not between", value1, value2, "ownerid");
            return (Criteria) this;
        }

        public Criteria andSavedIsNull() {
            addCriterion("saved is null");
            return (Criteria) this;
        }

        public Criteria andSavedIsNotNull() {
            addCriterion("saved is not null");
            return (Criteria) this;
        }

        public Criteria andSavedEqualTo(Integer value) {
            addCriterion("saved =", value, "saved");
            return (Criteria) this;
        }

        public Criteria andSavedNotEqualTo(Integer value) {
            addCriterion("saved <>", value, "saved");
            return (Criteria) this;
        }

        public Criteria andSavedGreaterThan(Integer value) {
            addCriterion("saved >", value, "saved");
            return (Criteria) this;
        }

        public Criteria andSavedGreaterThanOrEqualTo(Integer value) {
            addCriterion("saved >=", value, "saved");
            return (Criteria) this;
        }

        public Criteria andSavedLessThan(Integer value) {
            addCriterion("saved <", value, "saved");
            return (Criteria) this;
        }

        public Criteria andSavedLessThanOrEqualTo(Integer value) {
            addCriterion("saved <=", value, "saved");
            return (Criteria) this;
        }

        public Criteria andSavedIn(List<Integer> values) {
            addCriterion("saved in", values, "saved");
            return (Criteria) this;
        }

        public Criteria andSavedNotIn(List<Integer> values) {
            addCriterion("saved not in", values, "saved");
            return (Criteria) this;
        }

        public Criteria andSavedBetween(Integer value1, Integer value2) {
            addCriterion("saved between", value1, value2, "saved");
            return (Criteria) this;
        }

        public Criteria andSavedNotBetween(Integer value1, Integer value2) {
            addCriterion("saved not between", value1, value2, "saved");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table course
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 18 23:53:07 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table course
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}