package com.bpf.pojo;

import java.io.Serializable;

public class Owner implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.id
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.mid
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    private String mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.name
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table owner
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.id
     *
     * @return the value of owner.id
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.id
     *
     * @param id the value for owner.id
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.mid
     *
     * @return the value of owner.mid
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.mid
     *
     * @param mid the value for owner.mid
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public void setMid(String mid) {
        this.mid = mid == null ? null : mid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.name
     *
     * @return the value of owner.name
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.name
     *
     * @param name the value for owner.name
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owner
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", mid=").append(mid);
        sb.append(", name=").append(name);
        sb.append("]");
        return sb.toString();
    }
}