package com.bpf.pojo;

import java.io.Serializable;

public class PageWithBLOBs extends Page implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page.videoUrl
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    private String videourl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page.audioUrl
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    private String audiourl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table page
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page.videoUrl
     *
     * @return the value of page.videoUrl
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public String getVideourl() {
        return videourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page.videoUrl
     *
     * @param videourl the value for page.videoUrl
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public void setVideourl(String videourl) {
        this.videourl = videourl == null ? null : videourl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page.audioUrl
     *
     * @return the value of page.audioUrl
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public String getAudiourl() {
        return audiourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page.audioUrl
     *
     * @param audiourl the value for page.audioUrl
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public void setAudiourl(String audiourl) {
        this.audiourl = audiourl == null ? null : audiourl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", videourl=").append(videourl);
        sb.append(", audiourl=").append(audiourl);
        sb.append("]");
        return sb.toString();
    }
}