package com.bpf.pojo;

import java.io.Serializable;

public class Page implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page.cid
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page.pageNo
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    private Integer pageno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page.part
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    private String part;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page.duration
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    private Integer duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page.width
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    private Integer width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page.height
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    private Integer height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page.quality
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    private String quality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page.bvid
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    private String bvid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table page
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page.cid
     *
     * @return the value of page.cid
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page.cid
     *
     * @param cid the value for page.cid
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page.pageNo
     *
     * @return the value of page.pageNo
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public Integer getPageno() {
        return pageno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page.pageNo
     *
     * @param pageno the value for page.pageNo
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public void setPageno(Integer pageno) {
        this.pageno = pageno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page.part
     *
     * @return the value of page.part
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public String getPart() {
        return part;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page.part
     *
     * @param part the value for page.part
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public void setPart(String part) {
        this.part = part == null ? null : part.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page.duration
     *
     * @return the value of page.duration
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page.duration
     *
     * @param duration the value for page.duration
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page.width
     *
     * @return the value of page.width
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page.width
     *
     * @param width the value for page.width
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page.height
     *
     * @return the value of page.height
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page.height
     *
     * @param height the value for page.height
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page.quality
     *
     * @return the value of page.quality
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public String getQuality() {
        return quality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page.quality
     *
     * @param quality the value for page.quality
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public void setQuality(String quality) {
        this.quality = quality == null ? null : quality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page.bvid
     *
     * @return the value of page.bvid
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public String getBvid() {
        return bvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page.bvid
     *
     * @param bvid the value for page.bvid
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    public void setBvid(String bvid) {
        this.bvid = bvid == null ? null : bvid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbg.generated Thu Nov 18 23:53:07 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cid=").append(cid);
        sb.append(", pageno=").append(pageno);
        sb.append(", part=").append(part);
        sb.append(", duration=").append(duration);
        sb.append(", width=").append(width);
        sb.append(", height=").append(height);
        sb.append(", quality=").append(quality);
        sb.append(", bvid=").append(bvid);
        sb.append("]");
        return sb.toString();
    }
}